version: '3.3'

volumes:
  postgres_data:
  static_files:
  media_files:

services:

  db:
    image: postgres:12.4
    container_name: foodgram_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: hnthh/foodgram-backend:latest
    container_name: foodgram_backend
    restart: always
    depends_on:
      - db
    volumes:
      - ../backend/ingredients/migrations/:/code/ingredients/migrations/
      - ../backend/recipes/migrations/:/code/recipes/migrations/
      - ../backend/tags/migrations/:/code/tags/migrations/
      - ../backend/users/migrations/:/code/users/migrations/

      - static_files:/code/static/
      - media_files:/code/media/
    env_file:
      - .env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    container_name: foodgram_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_files:/static/
      - media_files:/media/
    depends_on:
      - backend
