name: Foodgram-app workflow

on: [push, workflow_dispatch]

jobs:
  tests:
    name: Test an app and install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Manage deps
        run: make deps

      - name: Apply isort, flake8
        run: make lint

#      - name: Test with PyTest
#        env:
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
#          SQLITE_DATABASE_URL: ${{ secrets.SQLITE_DATABASE_URL }}
#        run: make coverage

      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v2
#        with:
#          directory: /home/runner/work/foodgram-project-react/backend/
#          flags: pytest
#          name: codecov-umbrella
#          fail_ci_if_error: true

  push_to_docker_hub:
    name: Push Docker image to DockerHub
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push backend to DockerHub
      uses: docker/build-push-action@v2
      with:
        file: 'backend/Dockerfile'
        push: true
        tags: hnthh/foodgram-backend:latest

  deploy:
    name: Deploy to a server via SSH
    runs-on: ubuntu-latest
    needs: push_to_docker_hub

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: 'infra/docker-compose.yml, infra/nginx.conf'
          overwrite: true
          target: 'foodgram'

      - name: Set up initial files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          stack_file_name: docker-compose.yaml
          script: |
            cd foodgram/infra

            sudo docker-compose stop backend
            sudo docker-compose rm -f backend
            sudo docker rmi hnthh/foodgram-backend:latest

            echo DEBUG=${{ secrets.DEBUG }} > .env
            echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env

            echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env

            sudo docker-compose up -d

            sudo docker-compose exec -T backend python manage.py makemigrations --noinput
            sudo docker-compose exec -T backend python manage.py migrate --noinput
            sudo docker-compose exec -T backend python manage.py collectstatic --noinput
